spring:
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:sqlite:mydb.db
    driver-class-name: org.sqlite.JDBC
    username: admin
    password: admin

  security:                    # ← jwt 아래가 아니라 spring 아래로 이동
    oauth2:
      client:
        registration:
          kakao:
            client-id: 469634aad6d64f41964842455dd11961
            client-secret: fEJmOqKB8wSAS6loXq595qsekhyXQZtG
            redirect-uri: "yourapp://oauth2redirect/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:                           # 이제 별도 블록
  secret-key: n7u1fHyzD4/E3QfZcpnIu1kzXG9xq0j5Ps8LQy0rY4Y=
  access-token-expire-time: 300
  refresh-token-expire-time: 7200
